apiVersion: v1
kind: Secret
metadata:
  name: clubhub-secrets
  namespace: clubhub
type: Opaque
stringData:
  JWT_SECRET: "clubhub_super_secret_key_must_be_at_least_32_chars!"
  MONGO_USER: "clubhub"
  MONGO_PASSWORD: "Cl9bHub_M0ngoPwd_2026"
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-secrets
  namespace: clubhub
type: Opaque
stringData:
  groq_api_key: "REPLACE_ME_WITH_REAL_KEY"
