---
apiVersion: v1
kind: Service
metadata:
  name: event-app
  namespace: clubhub
  labels: {app: event-app, tier: backend}
spec:
  selector: {app: event-app}
  ports:
    - {name: http, port: 8088, targetPort: 8088}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-app
  namespace: clubhub
  labels: {app: event-app, tier: backend}
spec:
  replicas: 1
  selector: {matchLabels: {app: event-app}}
  template:
    metadata: {labels: {app: event-app, tier: backend}}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - {key: kubernetes.io/hostname, operator: In, values: [k8s-worker-1]}
      containers:
        - name: app
          image: docker.io/rickknd/clubhub-event:v1
          imagePullPolicy: IfNotPresent
          ports: [{containerPort: 8088, name: http}]
          env:
            - {name: SPRING_PROFILES_ACTIVE, valueFrom: {configMapKeyRef: {name: clubhub-config, key: SPRING_PROFILES_ACTIVE}}}
            - {name: SPRING_DATA_MONGODB_URI, value: "mongodb://event-db:27017/eventdb"}
            - {name: USER_SERVICE_URL, value: "http://user-app:8081"}
            - {name: CLUB_SERVICE_URL, value: "http://club-app:8083"}
            - {name: JWT_SECRET, valueFrom: {secretKeyRef: {name: clubhub-secrets, key: JWT_SECRET}}}
            - {name: JAVA_OPTS, valueFrom: {configMapKeyRef: {name: clubhub-config, key: JAVA_OPTS}}}
          resources:
            requests: {memory: 256Mi, cpu: 100m}
            limits: {memory: 768Mi, cpu: 1000m}
          livenessProbe:
            httpGet: {path: /actuator/health/liveness, port: 8088}
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet: {path: /actuator/health/readiness, port: 8088}
            initialDelaySeconds: 30
            periodSeconds: 10
