apiVersion: batch/v1
kind: Job
metadata:
  name: prep-mongo-storage
  namespace: clubhub
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-1
      containers:
        - name: prep
          image: docker.io/library/busybox:1.36
          command:
            - sh
            - -c
            - |
              mkdir -p /host/worker-storage/user-db
              mkdir -p /host/worker-storage/club-db
              mkdir -p /host/worker-storage/event-db
              mkdir -p /host/worker-storage/messaging-db
              chmod 777 -R /host/worker-storage
              ls -la /host/worker-storage/
              echo "Done."
          volumeMounts:
            - name: host
              mountPath: /host
      volumes:
        - name: host
          hostPath:
            path: /mnt
            type: DirectoryOrCreate
