package clubhub.model;



import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

@Document(collection = "game_leaderboards")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class GameLeaderboard {

    @Id
    private String id;

    private String gameSessionId;
    private String conversationId;

    private List<LeaderboardEntry> entries = new ArrayList<>();

    private String aiGameSummary;       // Generated by Gemini

    @CreatedDate
    private Instant createdAt = Instant.now();

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class LeaderboardEntry {
        private String userId;
        private String username;
        private int totalPoints;
        private int correctAnswers;
        private int wrongAnswers;
        private long avgResponseTimeMs;
        private int rank;
        private String aiTitle;         // e.g. "Quiz Overlord 🏆", "Speed Demon ⚡"
    }
}
