package tn.esprit.clubhub.Entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * "Procès-Verbal" generated by the SECRETAIRE_GENERALE for a completed event.
 *
 * <p>The user fills in a short Q&A in any language (French / English /
 * Tunisian darija / Arabic). The custom rule-based NLP builder (or the
 * local LLM fallback) transforms those raw answers into a formal French
 * PV, and the result is stored here so it can be edited, re-generated,
 * downloaded as PDF, or deleted later.</p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "meeting_pvs")
public class MeetingPv {

    @Id
    private String id;

    /** Reference to the {@code Event} this PV documents. */
    private String eventId;

    /** Snapshot of the title at PV-creation time (events can be renamed later). */
    private String eventTitle;

    /** ISO date string of the event (yyyy-MM-dd) — denormalized for the list view. */
    private String eventDate;

    /** Identifier of the SECRETAIRE_GENERALE who authored the PV. */
    private String secretaryId;

    /** Display name of the secretary at the time of writing — denormalized. */
    private String secretaryName;

    /** Raw answers the secretary typed, in their original language. */
    private List<QaPair> qaPairs = new ArrayList<>();

    /** Free-form additional notes the secretary wanted to add (also fed to the LLM). */
    private String additionalNotes;

    /** The PV body produced by the AI pipeline, EDITABLE by the secretary before save. */
    private String generatedContent;

    /** Detected / chosen source language: fr | en | ar | tn | mixed. */
    private String sourceLanguage;

    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class QaPair {
        private String question;
        /** "oui" / "non" / "sans avis" for yesno — free text otherwise. */
        private String answer;
        /** Optional stable identifier (e.g. "venue_ok") to remap answers across re-edits. */
        private String questionId;
        /** "yesno" | "text" — drives the rendering on the frontend. Defaults to "text". */
        private String type;
        /** PV section the question belongs to (préambule / déroulement / …). */
        private String section;
        /**
         * Free-text explanation the secretary types when answering "non".
         * The LLM will quote it verbatim instead of inventing a reason.
         */
        private String explanation;

        public QaPair(String question, String answer) {
            this.question = question;
            this.answer = answer;
            this.type = "text";
        }
    }
}
